// <auto-generated />
namespace StudentskaSluzba.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class GodinaAndBrojUpisafromstringtoint : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GodinaAndBrojUpisafromstringtoint));
        
        string IMigrationMetadata.Id
        {
            get { return "202111201239017_Godina And BrojUpisa from string to int"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
